server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: car-service-route
          uri: lb://car-service
          predicates:
            - Path=/api/cars/**

        - id: customer-service-route
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**

        - id: renting-service-route
          uri: lb://renting-service
          predicates:
            - Path=/api/renting/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true